### PR TITLE
Small Cleanup

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
<br>

### Changes

- Moved GitHub pages content into `/docs/` folder
  
  *Please adjust the source direction in the settings*

- Converted raw links into link references

<br>
<br>

### Repository Suggestions

- ***[Disable Unused Widgets][Widgets]***:

  - `Packages`

  - `Releases`
  
  <br>

- ***[Disable Unused Tabs][Tabs]***:

  - `Projects`

  - `Wiki`

[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md

### CODE REVIEW

**Comment by quinton-ashley** [comment]
My website depends on the contents being top level. Moving the links in the README was great though thanks!

**Comment by ElectronicsArchiver** [comment]
> My website depends on the contents being top level. 

Github pages allows you to use the root and docs folder though?

**Comment by quinton-ashley** [comment]
Nothing in this repo could be considered documentation, it's all just core QuintOS. I serve all the files in this repo from the root folder to my website (found in the quintos-web repo) and it doesn't make sense to put any of it in a docs folder.

**Comment by ElectronicsArchiver** [comment]
In this case 'docs' refers to 'documents' and is the standard way GitHub names the GitHub pages source folder.

**Comment by quinton-ashley** [comment]
ooo I see. Still from the viewpoint that this repo is also an npm package it still doesn't make sense to put source code in a documents folder.

**Pull request merged**
